version: "3.0"

volumes:
  # Named volume containing kubeconfig, shared by different containers 
  kube:

services:
  # Local Docker registry    
  # Just tag your image as localhost:5000/<image name>
  local-registry:
    image: "registry:2.7.1"
    ports:
    - "5000:5000"

  # Kubernetes control plane
  server:
    image: "rancher/k3s:v1.22.7-k3s1"
    command: server --disable traefik
    privileged: true
    environment:
    - K3S_TOKEN=k3stoken
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - "./k3s/registries.yaml:/etc/rancher/k3s/registries.yaml"
    - "kube:/output"
    ports: 
    - "6443:6443"
    - "80:80"

  # Helper container for copying kubeconfig to host directory
  kubeconfig:
    image: alpine
    restart: on-failure
    volumes:
    - "kube:/.kube"
    - "/tmp:/tmp"
    entrypoint: sh -ec
    command: 
    - |
      cp /.kube/kubeconfig.yaml /tmp/kubeconfig
      chmod 666 /tmp/kubeconfig

  # Kubernetes worker nodes
  agent:
    image: "rancher/k3s:v1.22.7-k3s1"
    deploy:
      replicas: 3
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=k3stoken
    volumes:
    - "./k3s/registries.yaml:/etc/rancher/k3s/registries.yaml"
