name: curl-jq
on:
  push:
    paths:
      - ".github/workflows/curljq.yaml"
      - "curl-jq/**"
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/ashwinath
      IMAGE_NAME: curl-jq
      IMAGE_TAG: v0.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push
      working-directory: curl-jq
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
